[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --workspace=packages/api"]

[phases.build]
cmds = ["npm run build --workspace=packages/api"]

[start]
cmd = "node packages/api/dist/index.js"
