[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build --workspace=apps/web && npm run build --workspace=packages/api"]

[start]
cmd = "npx drizzle-kit push && node packages/api/dist/index.js"
